---


- hosts: nginxsevs
  vars: 
    - servicio: nginx
  become: yes
  tasks:

    - name: instalar nginx
      dnf:
        name: "{{servicio}}*"
        state: present
         
    - name: nueva pagina
      template:
        src: ./templates/template.j2
        dest: /usr/share/nginx/html/index.html
      notify: 
      - reiniciar nginx


    - name: permitir puerto
      firewalld:
        zone: public
        port: "{{item.port}}"
        permanent: yes
        state: "{{ item.state }}"
      loop: "{{ firewall_ports }}"

    - name: iniciar nginx
      service:
        name: "{{servicio}}"
        state: started


  handlers:
    - name: reiniciar nginx
      service:
        name: "{{servicio}}"
        state: restarted
