---


- hosts: all
  vars: 
    - servicio: nginx
  become: yes
  tasks:

    - name: instalar nginx
      ansible.builtin.dnf:
        name: "{{servicio}}*"
        state: present
         
    - name: nueva pagina
      template:
        src: ./templates/template.j2
        dest: /usr/share/nginx/html/index.html
      notify: 
      - reiniciar nginx


    - name: permitir puerto
      ansible.posix.firewalld:
        zone: public
        port: "{{ item }}"
        permanent: yes
        state: enabled
      loop:
        - 80/tcp
        - 8080/tcp

    - name: iniciar nginx
      service:
        name: "{{servicio}}"
        state: started


  handlers:
    - name: reiniciar nginx
      service:
        name: "{{servicio}}"
        state: restarted
